### ISSUE TITLE
Node Microservices using Hydra

### ISSUE THREAD

**Issue by nosamanuel** [CondeNast/atx-lunchnlearn#15]
From EmpireJS (31:24).

https://www.youtube.com/watch?list=PL31ehRjJCA6Ez9Y_dZWymd_LDV7Ydc_0D&v=j_yVf9Blcjo

**Comment by crccheck** [comment]
I didn't really like this talk since it was very tool specific and going through live demos. If you're interested in just knowing what tools exist, we can do the old "play ten minutes then decide if we want to finish the video"

NOTE isme:
![screen shot 2016-12-07 at 11 28 36 am](https://cloud.githubusercontent.com/assets/189908/20978920/5508b2e4-bc70-11e6-9c4f-7905f47fbb56.png)

**Comment by nosamanuel** [comment]
I originally thought this was related to http://www.hydra-cg.com/ but it looks like it's totally different, although confusingly also in the web API space.

I bookmarked this article about the tool from the video if anybody is interested in pursuing it independently: https://community.risingstack.com/tutorial-building-expressjs-based-microservices-using-hydra/.
